apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: canary-rollouts-realmytrip
        image: ddung1203/realmytrip:14
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: canary
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: canary-rollout
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: canary-rollout
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50